--- @alias EventPump fun(event:Event) A function that handles and dispatches incoming events.

--- Creates a new event object.
--- @param type string The name of the type of event.
--- @param input table Contextual data to be used by the event handler.
--- @param output table Intent generated by the event handler.
--- @return Event event The new event object.
local function new(type,input,output)
	--- @class Event A generic event object that can be used to create a layer of separation between the main program and subscripts.
	--- @field type string The name of the type of event.
	--- @field input table Contextual data to be used by the event handler.
	--- @field output table Intent generated by the event handler.
	local event = {
		type = type,
		input = input,
		output = output or {},
	}
	return event
end

return {
	new = new,
}